#theme: jekyll-theme-cayman
#theme: chalk
remote_theme: nielsenramon/chalk/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
